Add accelerate to requirements
Latest version of transformers (v4.51.0) now depends on accelerate

This has been reported and fixed in transformers main branch and will be released as patch.
This is a stop gap solution to keep the CI builds working.
https://github.com/huggingface/transformers/issues/37326

Specific errors when running tests:

File "/***/***-venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4333, in from_pretrained
  model_init_context = cls.get_init_context(is_quantized, _is_ds_init_called)
File "/***/***-venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3736, in get_init_context
  init_contexts = [no_init_weights(), init_empty_weights()]
NameError: name 'init_empty_weights' is not defined